[package]
name = "server"
version = "0.1.0"
authors = ["Coleman McFarland <coleman.mcfarland@gmail.com>"]

[dependencies]
bincode = "*"
sled = "*" 
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde_derive = "*"
serde_json = "*"
serde = "*"
maud = { git = "https://github.com/CJStadler/maud.git", branch = "enable-proc-macro-non-items-flag", features = ["rocket"] }
tempdir = "*"
