[package]
name = "ui"
version = "0.1.0"
authors = ["Coleman McFarland <coleman.mcfarland@gmail.com>"]


[dependencies]
strum = "0.8.0"
strum_macros = "0.8.0"
serde = "1"
serde_derive = "1"
# I think TOML wants the { ... } inline map to be on a single line
yew = { git = "https://github.com/DenisKolodin/yew.git", rev = "f1dcb7234c4933d2daa170dd513a921451ee641e" }
stdweb = "0.3"

[[bin]]
name = "ui"
path = "src/main.rs"
kind = ["bin", "proc-macro"]
